### ISSUE TITLE
raise ValueError('Resize method is not implemented.')

### ISSUE THREAD

**Issue by pongopal** [krishnabits001/task_driven_data_augmentation#4]
Traceback (most recent call last):
  File "tr_deformation_cgan_and_unet.py", line 196, in <module>
    lamda_dsc=parse_config.lamda_dsc,lamda_adv=parse_config.lamda_adv,lamda_l1_g=parse_config.lamda_l1_g)
  File "../models.py", line 377, in spatial_generator_cgan_unet
    gen_up5 = layers.upsample_layer(ip_layer=gen_fcn_reshaped, method=self.interp_val, scale_factor=scale_val)
  File "../layers_bn.py", line 161, in upsample_layer
    op = tf.image.resize_images(images=ip_layer,size=[new_height,new_width],method=method)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1187, in resize_images
    skip_resize_if_same=True)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1095, in _resize_images_common
    images = resizer_fn(images, size)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1179, in resize_fn
    raise ValueError('Resize method is not implemented.')
ValueError: Resize method is not implemented.

**Comment by krishnabits001** [comment]
Hi,

Thanks for the question.
The functions in the codebase were implemented for tensorflow version 1.8.0 and code works fine for the 1.8.0 version.
If your tensorflow version is higher than 1.8.0, please update the functions accordingly.
For resize function:
You need to update the line no. 161 from
op = tf.image.resize_images(images=ip_layer,size=[new_height,new_width],method=method)

to

op = tf.image.resize_images(images=ip_layer,size=[new_height,new_width],method=ResizeMethod.BILINEAR)
